server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
        server:
          git:
            uri: https://github.com/vamsikrish-A/config-server
            clone-on-start: true